### ISSUE TITLE
Embroider Compatibility

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-template-imports/ember-template-imports#12]
Keeping track of tasks for getting this to work with embroider:

atm, when _only_ having *.gjs files, and running with embroider, the `ember-template-imports` addon cannot be found:

```
Build Error (PackagerRunner) in components/switch.js

Module not found: Error: Can't resolve 'ember-template-imports' in '$TMPDIR/embroider/70b3f0/components'
```

This occurred in a file that had:
```js
import { hbs } from 'ember-template-imports';
```

**Comment by dfreeman** [comment]
I'm also hitting this error even just using plain `.js` files with no `.gjs` at all 🤔

**Comment by chriskrycho** [comment]
cc. @rwjblue – I'm happy to dig in and help get this sorted, as getting this working for our app is basically one of two things Up Next For Me™ this quarter.

**Comment by ef4** [comment]
One tip for someone who wants to work on this: 

This package will need a babel plugin that rewrites from the specific template-imports formats to JS containing `precompileTemplate`. When you want to get the `precompileTemplate` function, use https://github.com/ef4/babel-import-util/. There are examples of how to use it [here](https://github.com/emberjs/babel-plugin-ember-template-compilation/blob/572cbe4f65d4dce407ce806088ecd42d2dd86656/src/plugin.ts) as well as a couple spots within embroider itself. It takes care of some otherwise tricky minutiae in telling babel to update its bindings so that this babel plugin will compose correctly with the others.

**Comment by chriskrycho** [comment]
@dfreeman, I believe we can mark this as closed now? 🎉

**Comment by dfreeman** [comment]
Yes!
