### ISSUE TITLE
Guidance for using built-in components & helpers

### ISSUE THREAD

**Issue by HeroicEric** [ember-template-imports/ember-template-imports#13]
I was playing around with this and ran into some cases where I wanted to use built-in helpers & components that I wasn't sure how to handle.

### Built-in helpers

Trying to use the `{{get}}` helper but I wasn't sure where to import them from, if that's even possible yet.

Error in the devtools console if you try to use without importing it from somewhere:

```
opcode-compiler.js:499 Uncaught Error: Attempted to resolve a component or helper in a strict mode template, but that value was not in scope: get
```

### Built-in components

Another case that came up was trying to use the built-in `<LinkTo />` component. I tried `import Link from '@ember/routing/link-component';` but that didn't seem to work, resulting in the following build error:

```
Build Error (broccoli-persistent-filter:Babel > [Babel: ember-octable]) in ember-octable/components/octable.js

/Users/ekelly02/code/open-source/ember-octable/ember-octable/components/octable.js: Attempted to invoke a component that was not in scope in a strict mode template, `<LinkTo>`. If you wanted to create an element with that name, convert it to lowercase - `<linkto>`:

|
|  <LinkTo @route="index">Foo</LinkTo>
|

(error occurred in 'an unknown module' @ line 7 : column 14)
````

**Comment by pzuraq** [comment]
This section of the strict-mode RFC covers both keywords and built-in helpers and components. In the case of built-in helpers and components, they will need to be imported, and referred to directly. Currently the imports have not been implemented, there is a PR out for adding them to the imports transform: https://github.com/ember-cli/ember-rfc176-data/pull/364

For the second case, the import should have worked because `Link` was exposed. Note that you have to import it with the _same name_ that you use it with in your component, this would not work:

```js
import Link from '@ember/routing/link-component';

<template>
  <LinkTo @route="index">Foo</LinkTo>
</template>
```

But _this_ would:

```js
import Link from '@ember/routing/link-component';

<template>
  <Link @route="index">Foo</Link>
</template>
```

You can name the component anything you want, strict mode templates don't care. It can be lower case, upper case, any valid JS identifier 😄 

If it's still not working, then there may be a bug.

**Comment by HeroicEric** [comment]
@pzuraq Thanks for the info, that makes sense.

I did try to use the link-to component again, making sure that the local name matched up and still couldn't get it to work.

```js
import Component from '@glimmer/component';
import Link from '@ember/routing/link-component';
import { hbs } from 'ember-template-imports';

export default class TestComponent extends Component {
  static template = hbs`
    <Link @route="index">Test</Link>
  `;
}
```

**Comment by pzuraq** [comment]
So for the time being, we're actually completely rewriting Ember 2.27 to remove the modules API polyfill 😄 so that _may_ fix this issue, we'll see. If it does not, we should definitely look into it, but if it does, I'd like to avoid trying to figure out what the ordering issue is, Babel plugin ordering is really very difficult to address

**Comment by junyper** [comment]
I'm not sure if this is the same issue, but I am getting a similar error with the 'on' modifier here: https://github.com/junyper/ember-playground/blob/main/app/components/button/index.js#L24

Is there any way to work around this?

**Comment by knownasilya** [comment]
How does one import `{{on}}`?

**Comment by NullVoxPopuli** [comment]
Here are all the imports: https://github.com/emberjs/rfcs/pull/496/files#diff-f1be2bfd87e50eff6f90cff8cf7ab910631693a7fa6bbc03bcae794824fd3a7eR477

**Comment by knownasilya** [comment]
Can we add these to the range, or a link to this section?

**Comment by NullVoxPopuli** [comment]
Yea, I'll put up a PR

**Comment by NullVoxPopuli** [comment]
PR: https://github.com/ember-template-imports/ember-template-imports/pull/27

**Comment by knownasilya** [comment]
Nice
